### ISSUE TITLE
Absolute paths not working on Windows

### ISSUE THREAD

**Issue by crystalfp** [slevey087/plugin-please#1]
First of all, thanks for this module that solves my application problems in an elegant way!

I work on windows. My cwd is `D:/projects/exp`
Here I have a subdirectory `plugins`.
When I start the module with:
```
const pluginManager = require("plugin-please")("D:/projects/exp/plugins");
```
I received this error:
`Error: ENOENT: no such file or directory, scandir 'D:\projects\exp\D:\projects\exp\plugins'`
Nothing changes if I prepend to my path a slash or remove `D:`

Any suggestion?
Thanks!
mario

**Comment by slevey087** [comment]
Sorry for the delay, but this should be fixed now in version 0.2.0. Glad you like the package!
